title: Lisa Rodriguez
logo: "/images/carrofoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Robotics and Digital Systems Engineer Student at Instituo Tecnologico de Estudios Superiores de Monterrey
  <br><br>
  <a href="https://www.linkedin.com/in/matt-chapman-ba8488118/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'