logo: "/images/carrofoto.jpg?raw=true" # your photo (or logo) here
title: Lisa Rodriguez
title_color: '#000000'
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Robotics and Digital Systems Engineer Student at Instituo Tecnologico de Estudios Superiores de Monterrey | C++, C#, Python, VHDL, MATLAB, Simulink, R
  <br><br>
  <a href="https://www.linkedin.com/in/lisa-rodriguez-47678a307?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app ">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'